# Generated by Django 3.1.7 on 2021-03-20 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20210320_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='created_by',
        ),
    ]
