# Generated by Django 3.1.7 on 2021-03-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_remove_request_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='approved',
        ),
        migrations.AddField(
            model_name='request',
            name='response',
            field=models.CharField(blank=True, choices=[(1, 'Approve'), (3, 'Pending'), (2, 'Decline')], max_length=200, null=True),
        ),
    ]
