# Generated by Django 3.1.7 on 2021-03-21 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0008_auto_20210321_2040'),
        ('staff', '0004_auto_20210320_0933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='request',
            name='response',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approve', 'Approve'), ('Decline', 'Decline')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_branch', to='vehicle.branches')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
