# Generated by Django 3.1.7 on 2021-03-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20210321_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='response',
            field=models.CharField(blank=True, choices=[('Decline', 'Decline'), ('Approve', 'Approve'), ('Pending', 'Pending')], max_length=200, null=True),
        ),
    ]
