# Generated by Django 3.1.7 on 2021-03-21 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20210321_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='staff.staff'),
        ),
        migrations.AlterField(
            model_name='request',
            name='response',
            field=models.CharField(blank=True, choices=[('Approve', 'Approve'), ('Pending', 'Pending'), ('Decline', 'Decline')], max_length=200, null=True),
        ),
    ]
