# Generated by Django 3.1.7 on 2021-03-21 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0008_auto_20210322_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='response',
            field=models.CharField(blank=True, choices=[('Decline', 'Decline'), ('Pending', 'Pending'), ('Approve', 'Approve')], max_length=200, null=True),
        ),
    ]
