# Generated by Django 3.1.7 on 2021-03-26 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0014_auto_20210326_2309'),
        ('staff', '0010_auto_20210326_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='response',
            field=models.CharField(blank=True, choices=[('Decline', 'Decline'), ('Pending', 'Pending'), ('Approve', 'Approve')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='vehicle_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_vehicle', to='vehicle.vehicle'),
        ),
    ]
