# Generated by Django 3.1.7 on 2021-04-01 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0011_auto_20210326_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='vehicle_issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_issue', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='response',
            field=models.CharField(blank=True, choices=[('Declined', 'Declined'), ('Approved', 'Approved'), ('Pending', 'Pending')], max_length=200, null=True),
        ),
    ]
