# Generated by Django 3.1.7 on 2021-04-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_auto_20210401_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='response',
            field=models.CharField(blank=True, choices=[('Declined', 'Declined'), ('Approved', 'Approved'), ('Pending', 'Pending'), ('Completed', 'Completed')], max_length=200, null=True),
        ),
    ]
