# Generated by Django 3.1.7 on 2021-04-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_auto_20210418_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='time_of_return',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
