# Generated by Django 3.1.7 on 2021-04-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_request_time_of_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='time_received',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='response',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Canceled', 'Canceled'), ('Completed', 'Completed'), ('Pending', 'Pending'), ('Declined', 'Declined')], max_length=200, null=True),
        ),
    ]
