# Generated by Django 3.1.7 on 2021-02-25 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'branches',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('colour', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='vehicle/')),
                ('yr_of_manufacture', models.DateTimeField(blank=True, null=True)),
                ('procurement_date', models.DateTimeField(blank=True, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=250, null=True)),
                ('time_of_collection', models.DateTimeField(blank=True, null=True)),
                ('time_of_return', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=300, null=True)),
                ('return_condition', models.CharField(blank=True, choices=[(2, 'Damaged'), (1, 'Intact')], max_length=50, null=True)),
                ('available', models.BooleanField(blank=True, default=True, null=True)),
                ('sent_for_maintenance', models.BooleanField(blank=True, default=False, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_branch', to='vehicle.branches')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_vehicles', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receive_vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('brought_back_date', models.DateTimeField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintain_vehicle', to='vehicle.vehicle')),
            ],
            options={
                'db_table': 'maintenance',
            },
        ),
    ]
