# Generated by Django 3.1.7 on 2021-03-19 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0003_auto_20210319_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
