# Generated by Django 3.1.7 on 2021-03-19 23:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0005_auto_20210320_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branches',
            name='staff',
        ),
        migrations.AddField(
            model_name='branches',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='branch_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='return_condition',
            field=models.CharField(blank=True, choices=[(2, 'Damaged'), (1, 'Intact')], max_length=50, null=True),
        ),
    ]
