# Generated by Django 3.1.7 on 2021-03-21 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0011_auto_20210322_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='return_condition',
            field=models.CharField(blank=True, choices=[(1, 'Intact'), (2, 'Damaged')], max_length=50, null=True),
        ),
    ]
