# Generated by Django 3.1.7 on 2021-03-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0012_auto_20210322_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='return_condition',
            field=models.CharField(blank=True, choices=[(2, 'Damaged'), (1, 'Intact')], max_length=50, null=True),
        ),
    ]
