# Generated by Django 3.1.7 on 2021-04-18 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0014_auto_20210326_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='return_condition',
            new_name='condition',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='issued_by',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='time_of_collection',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='time_of_return',
        ),
    ]
