# Generated by Django 3.1.7 on 2021-06-03 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0016_auto_20210603_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance',
            old_name='created_by',
            new_name='approved_by',
        ),
        migrations.RenameField(
            model_name='maintenance',
            old_name='created_at',
            new_name='date_brought_back',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='brought_back_date',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='description',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='sent_date',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='date_sent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='is_maintained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='reason',
            field=models.CharField(blank=True, choices=[('Repairs', 'Repairs'), ('Maintenance', 'Maintenance')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='condition',
            field=models.CharField(blank=True, choices=[(1, 'Intact'), (2, 'Damaged')], max_length=50, null=True),
        ),
    ]
