# Generated by Django 3.1.7 on 2021-06-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0017_auto_20210603_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='is_maintained',
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='reason',
            field=models.CharField(blank=True, choices=[('Maintenance', 'Maintenance'), ('Repairs', 'Repairs')], max_length=250, null=True),
        ),
    ]
