# Generated by Django 3.1.7 on 2021-06-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0018_auto_20210603_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='date_brought_back',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='reason',
            field=models.CharField(blank=True, choices=[('Repairs', 'Repairs'), ('Maintenance', 'Maintenance')], max_length=250, null=True),
        ),
    ]
