# Generated by Django 3.1.7 on 2021-06-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0020_auto_20210603_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='date_brought_back',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='condition',
            field=models.CharField(blank=True, choices=[(1, 'Intact'), (2, 'Damaged')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='MaintenanceReturn',
        ),
    ]
