# Generated by Django 3.1.7 on 2021-06-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0023_auto_20210603_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='last_date_maintained',
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='reason',
            field=models.CharField(blank=True, choices=[('Repairs', 'Repairs'), ('Maintenance', 'Maintenance')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='condition',
            field=models.CharField(blank=True, choices=[(1, 'Intact'), (2, 'Damaged')], max_length=50, null=True),
        ),
    ]
