# Generated by Django 3.1.7 on 2021-03-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210317_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('AC', 'Active'), ('IN', 'Inactive')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('GM', 'General Manager'), ('St', 'Staff'), ('M', 'Manager')], max_length=255, null=True),
        ),
    ]
