# Generated by Django 3.1.7 on 2021-03-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210321_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('AC', 'Active'), ('IN', 'Inactive')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('St', 'Staff'), ('M', 'Manager'), ('GM', 'General Manager')], max_length=255, null=True),
        ),
    ]
