# Generated by Django 3.1.7 on 2021-04-18 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210324_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('St', 'Staff'), ('GM', 'General Manager'), ('M', 'Manager')], max_length=255, null=True),
        ),
    ]
